# Generated by Django 4.2.19 on 2025-03-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_commentmodel_replymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='conatactlist',
            name='icon',
            field=models.CharField(default='', max_length=200),
        ),
    ]
